# Generated by Django 4.2.1 on 2023-06-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(default='', upload_to='img/perfil'),
            preserve_default=False,
        ),
    ]
