# Generated by Django 4.2.1 on 2023-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='razonsocial',
            field=models.CharField(max_length=150),
        ),
    ]
