# Generated by Django 4.2.1 on 2023-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0003_alter_hotel_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
