# Generated by Django 4.2.1 on 2023-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0004_alter_hotel_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='domicilio',
            field=models.CharField(max_length=150),
        ),
    ]
