# Generated by Django 4.2.1 on 2023-05-19 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0005_alter_empleado_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cuil',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='CUIL inválido', regex='^(20|2[3-7]|30|3[3-4])(\\d{8})(\\d)$')]),
        ),
    ]
