# Generated by Django 4.2.1 on 2023-05-19 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('habitacionId', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('piso', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(default='Disponible', max_length=50)),
                ('precio', models.IntegerField()),
                ('hotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.hotel')),
            ],
            options={
                'verbose_name': 'Habitaciones de un hotel',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitacion',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reservaId', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateField(default=datetime.date.today)),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.cliente')),
            ],
            options={
                'verbose_name': 'Reservas de habitacinoes en un hotel',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('tipoHabitacionId', models.AutoField(primary_key=True, serialize=False)),
                ('tipoHabitacion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipos de habitaciones de un hotel',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='ReservaPorHabitacion',
            fields=[
                ('reservaHabitacionId', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIngreso', models.DateField()),
                ('fechaEgreso', models.DateField()),
                ('habitacionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionReservas.habitacion')),
                ('reservaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionReservas.reserva')),
            ],
            options={
                'verbose_name': 'Habitaciones en una reserva',
                'verbose_name_plural': 'reserva_habitaciones',
                'db_table': 'reserva_habitacion',
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipoHabitacionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionReservas.tipohabitacion'),
        ),
        migrations.AddConstraint(
            model_name='reservaporhabitacion',
            constraint=models.CheckConstraint(check=models.Q(('fechaIngreso__gte', django.db.models.functions.datetime.Now()), ('fechaIngreso__lte', models.F('fechaEgreso'))), name='Correctas fecha de reserva'),
        ),
    ]
